### ISSUE TITLE
Missing/broken "?" icon on etsdemo app

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traitsui#1122]
Steps to reproduce
---------------------

- `edm envs create ets-demo-app` (creates a python 3.6 environment)
- `edm install -e ets-demo-app etsdemo pyqt5 eam` (`eam` is optional)
- `edm run -e ets-demo-app -- pip install --upgrade git+http://github.com/enthought/traitsui.git#egg=traitsui`
- Launch the application

![broken-icon-etsdemo](https://user-images.githubusercontent.com/1926457/89759487-d2f12980-dad9-11ea-8244-8eeb43bab33e.png)

Observed on Win 10.

**Comment by kitchoi** [comment]
If you click the "TraitsUI Demo" node, is the image displayed?

**Comment by kitchoi** [comment]
(Not observed on OSX, now I am suspecting platform dependent file path separators not being handled properly.)

**Comment by rahulporuri** [comment]
> If you click the "TraitsUI Demo" node, is the image displayed?

Yes. If I click on the root-level "TraitsUI Demo" node, the icon is displayed.
If I click on the "Index" node at depth-1, the icon is displayed in an additional "Description" tab.

Only in "Traits ui demo" do I see the "?" missing icon.

**Comment by kitchoi** [comment]
Thank you. 
That's very helpful.  I believe this narrows things down to this object:
https://github.com/enthought/traitsui/blob/3e3a05a52215e33d88fab882e0f7f27638aa8eb4/ets-demo/etsdemo/app.py#L528-L532

Since the `path` is being used for constructing the HTML to be displayed, the path needs to conform to the [file URI scheme](https://en.wikipedia.org/wiki/File_URI_scheme), which is platform dependent.

**Comment by kitchoi** [comment]
Since it might be faster to fix this issue than commenting and speculating how this should be fixed, I went ahead to fix it 😅 . See #1131.
