### ISSUE TITLE
Update calls to super

### ISSUE THREAD

**Issue by rahulporuri** [enthought/traitsui#1167]
`super` has changed between Python 2 and 3. On 2, `super(ClassName, self)` was expected but on 3, `super()` works. These changes are similar to that in traits and envisage https://github.com/enthought/traits/pull/1280. Please use the regex mentioned in the traits PR to automated to search and replace - instead of making these changes by hand, manually.

**Comment by mdickinson** [comment]
Just a note: a _little_ bit of care is required, since historically we have had some instances where the explicit Python-2-version super call refers to something other than the current class in its first argument.

Any such instances are likely broken and need careful examination. But the main point is that there is potential for behaviour change as a result of the regex replacement.
