### ISSUE TITLE
UI Tester button click appearance

### ISSUE THREAD

**Issue by aaronayres35** [enthought/traitsui#1203]
The current implementation of button editor works as desired, however, if a user adds a delay to try and see their test run, there is no visual indication that a click occurred.  Without the tester, when a user clicks a button, it typically changes color while it is being clicked.  It would be nice if the tester was able to do this as well for visual confirmation the tester is clicking.  (it is clicking - we can tell by adding trait listeners, checking the values of traits etc.).  
This is purely a cosmetic issue.

**Comment by aaronayres35** [comment]
Qt has an animateClick method that may be useful.  I haven't gotten the chance to look at it closely or try it.

**Comment by kitchoi** [comment]
I'd be very careful with extending features beyond what is necessary for tests.  If it is easy to do with no added maintenance cost, that's fine... as long as we don't advertise this sort of visual behaviour as part of the tester feature, so we can back out if this gets in the way later. Otherwise this could be a slippery slope to emulating full interactions that reproduces a recording of actual user interactions.

**Comment by aaronayres35** [comment]
Closing because this feature is not worth the maintenance cost at the moment.  This would be an aesthetic improvement, and it does not really align with the current goals for the tester.  If, eventually, there is a stronger demand for this, this issue can be re-opened.
