### ISSUE TITLE
Add 'IsVisible` query class for UI Tester

### ISSUE THREAD

**Issue by aaronayres35** [enthought/traitsui#1291]
In some cases, an application/ui may have certain parts of the UI change between visible and not visible depending on the state of the UI.  It is likely that this behavior is something that one would want to verify with tests.

Note that all traitsui editors have a `visible` trait, but also toolkit specific elements (e.g. QtGui.Qwidgets) have `isVisible` methods.

**Comment by kitchoi** [comment]
The use case in tests might have meant to use Qt's `~isHidden` rather than `isVisible`. See the distinction [here](https://doc.qt.io/qt-5/qwidget.html#isHidden).
Wx has this `IsShownOnScreen` method, but I am not sure if it matches Qt's `~isHidden` or `IsVisible`.

**Comment by kitchoi** [comment]
> The use case in tests might have meant to use Qt's ~isHidden rather than isVisible. See the distinction here.
Wx has this IsShownOnScreen method, but I am not sure if it matches Qt's ~isHidden or IsVisible.

I am taking this back :) 
From the testing perspective, one wants to inspect if a widget or a container is visible to the user, and Qt `IsVisible` is the right thing to use: A widget can be invisible because one of its container widget is invisible.

For example:
```
Group(
    Item(..., visible_when="bool_item_1"),
    Item(..., visible_when="bool_item_2"),
    visible_when="bool_group",
)
```
A query of `IsVisible` should return false if `bool_item_1` is evaluated as true but `bool_group` is evaluated as false, because that is what a test would want to check: Check what the user can actually see.

(Coming back to this issue because I am seeing more use cases for this feature. See #1490 for making an implementation will allow `IsVisible` query to be available to a more general set of GUI widget.)
