### ISSUE TITLE
Add flag to turn off event processing in UI Wrapper

### ISSUE THREAD

**Issue by aaronayres35** [enthought/traitsui#1297]
There may be situations in which we don't want event handling to be done by UI Wrapper as it may already be handled by something else.  For example, if using UI Tester together with ModalDialogTester from pyface, both will independently try to process events which may cause problems.  Optionally disabling event processing on UI Wrapper would address this.

**Comment by kitchoi** [comment]
The story here is that if `UITester` / `UIWrapper` is used inside the `when_opened` callable given to `ModalDialogTester` for before closing the modal dialog, then we get into a race condition:
ModalDialogTester keeps polling whether the function that launches the modal dialog has returned (usually only happens if the dialog is closed in a test success scenario). It does so using a timer, which keep posting to the event loop until it is stopped.
But the UIWrapper tries to process the GUI events as long as there are any.
Consequently `when_opened` is blocked because there are always GUI events to be processed (posted by the timer), and the timer never dies because `when_opened` has not got to the point of closing the modal dialog.

**Comment by kitchoi** [comment]
Opt-ing out of event processing within `when_opened` makes sense because the test using ModalDialogTester is effectively driving the event processing already, there is no need to drive it again.
