### ISSUE TITLE
Incorrect search_path in example

### ISSUE THREAD

**Issue by aaronayres35** [enthought/traitsui#1432]
As mentioned in https://github.com/enthought/pyface/issues/830#issuecomment-738954788 and the subsequent comments on that issue, the search_path in `Image_editor_demo` refers to a non existent path in traits.  This leads to the image never being able to be located, and without https://github.com/enthought/pyface/pull/831 actually, causes the corresponding intergration test to fail on the latest pyface.

The path should be updated to: `search_path = [join(dirname(traitsui.api.__file__), '..', 'examples', 'demo', 'Extras')]`, and note to do this, `traitsui.api` must be imported directly.

**Comment by kitchoi** [comment]
If `traitsui` was installed with `pip install traitsui`, then `join(dirname(traitsui.api.__file__), ".."))` will likely be the `site-packages` folder in the Python environment, and the examples folder will not be found.

This would work: `search_path = [join(dirname(__file__))]`
Because `dirname(__file__)` is the folder where the example file is. Pyface looks for the `images` folder first: 
https://github.com/enthought/pyface/blob/8f6e9cd2cb3cbd33aced6cc5e0b4e0270eb1ffd3/pyface/resource/resource_manager.py#L105-L109
