### ISSUE TITLE
Remove demo tab from the etsdemo application

### ISSUE THREAD

**Issue by kitchoi** [enthought/traitsui#1454]
The demo tab works well when the content is like the examples from TraitsUI where there is always a GUI that can be run as a subpanel within the etsdemo.

However the UX is awkward for when the application is used against examples where there isn't a GUI, e.g. examples from traits.

The existence of the demo tab also adds a lot of complexity in the handling of the `if __name__ == "__main__"` block: When the run button is run and if there is a variable named `demo` or `popup`, the application skips the `__name__ == "__main__"` block because it wants to refresh the demo tab instead (see https://github.com/enthought/traitsui/issues/1428)

**Comment by corranwebster** [comment]
A simpler fix would be to have a flag that is set on the `DemoFile` object which shows or hides the demo tab using a `visible_when` depending on the availability of the `demo` object (eg. `"demo is not None"` might be good enough).  Although I fear this may not work because I seem to recall that `visible_when` is broken for `Tabbed` groups, but maybe this would be impetus to fix that.  Maybe the solution is to have larger sections of the UI swapped out if there is no `demo` value.

Alternatively, the demo app already supports different types of content with different views.  Currently this is based purely on file extension, but we could refactor it to use additional metadata about the file (either stored in the code somehow, or in an auxilliary configuration file).

**Comment by kitchoi** [comment]
I just realized that the proposal to removing the demo tab may also fix another UX issue noted in #1124.
I have commented in #1124 instead. @corranwebster Could you please comment what your thoughts are there?
