### ISSUE TITLE
Modern example using CheckBox Column with Qt5 backend

### ISSUE THREAD

**Issue by danieljfarrell** [enthought/traitsui#1542]
https://github.com/enthought/traitsui/blob/7a6d46ad10ea6c6b5a8dcc3b4939a9670c2a52ad/traitsui/extras/checkbox_column.py#L25

What are the options for using a checkbox column in modern TraitsUI code?

At the moment I am updating an old application that used TraitsUI 4 and the WX toolkit.

Do I have to specify the Qt4 toolkit? Ideally, I would like to target the toolkit which is getting the most attention from Enthought and I think this means Qt5.

**Comment by danieljfarrell** [comment]
Could be related to issue #435

**Comment by rahulporuri** [comment]
> Do I have to specify the Qt4 toolkit?

You don't have to. You can just install PyQt4 and barring unexpected issues, traitsui should just work.

> Ideally, I would like to target the toolkit which is getting the most attention from Enthought and I think this means Qt5.

We are paying more attention to Qt5 and Qt in general but we are also not removing support for Wx at the moment. If you run into issues with the Wx backend, please reach out to us.

Because Qt4 will not receive updates anymore (final version is 4.12.1 if im not wrong), we are prioritizing Qt5 support over Qt4. We might remove support for Qt4 entirely in the future but that's not going to happen anytime soon.

> Could be related to issue #435

Thanks for pointing out the existing issue. We'll try to look into it.

**Comment by danieljfarrell** [comment]
OK, thanks! So currently there are no options for using Qt5 with CheckboxColumn, without fixing issue #435, if I understand correctly?

**Comment by rahulporuri** [comment]
> OK, thanks! So currently there are no options for using Qt5 with CheckboxColumn, without fixing issue #435, if I understand correctly?

That's my understanding but i might be wrong.
