### ISSUE TITLE
NameErrors in the codebase

### ISSUE THREAD

**Issue by mdickinson** [enthought/traitsui#1751]
There are a few undefined names in the codebase, some of which were introduced quite recently:
```
./traitsui/wx/tree_editor.py:1261:26: F821 undefined name 'partial'
./traitsui/ui_editors/data_frame_editor.py:406:9: F821 undefined name 'warnings'
./traitsui/ui_editors/data_frame_editor.py:414:9: F821 undefined name 'warnings'
./traitsui/qt4/menu.py:133:39: F821 undefined name 'cur_id'
./traitsui/qt4/styled_date_editor.py:98:46: F821 undefined name 'date'
./traitsui/qt4/styled_date_editor.py:118:41: F821 undefined name 'date'
```

The first one was introduced in #1745 (see also #1746); the `warnings` references in #1560, and the `date` references in #524. The `partial` and `warnings` undefined names at least should be fixed before the next release - they have potential to break existing code.

**Comment by mdickinson** [comment]
And a meta-question: should our development process be picking up this kind of error *before* it's merged to the `main` branch? If so, what do we need to change to make sure that that happens?

**Comment by corranwebster** [comment]
Digging into this a bit right now: not really happy that the `setup.cfg` is nerfing so much of flake8 under any run.  Sort of want this to `python etstool.py flake8` to give me the "real" situation, and then have a "must pass" mode that is used in CI; but in the current mode we are using flake8 directly in CI.

So a possible proposal is:
- restructure `setup.cfg` so that it checks a limited set of codes that must pass for CI
- have `etstool.py` use this by default, but have an option to run in "strict" mode pointed at a config file with the end-goal flake8 state (eg. more-or-less what we have in Traits' `setup.cfg` less the file-specific exclusions)

**Comment by mdickinson** [comment]
> Digging into this a bit right now: not really happy that the `setup.cfg` is nerfing so much of flake8 under any run.

The part that surprised me most is that a targeted `flake8 some_file.py` doesn't override the list of exclusions, so it will silently pass if `some_file.py` has errors, but is listed under `exclude`. I couldn't find a way to get flake8 to tell me that it was skipping that file (other than using `-v`, which buries the information in a lot of other output).
