### ISSUE TITLE
Correct way to update slider range in UI (not updated after set_trait call)

### ISSUE THREAD

**Issue by KestutisMa** [enthought/traitsui#1806]
I want to change slider range.
`self.trait('t_pos').get_editor().high` is updated after `self.trait('t_pos').get_editor().trait_set(high=123)` 
(I see that from print output), but slider range in UI stays the same:

```
t_pos = Range(0, 222)
...
view = View(
... Item('t_pos', label='t', editor=RangeEditor(mode='slider', low=0, high=222)), 
...)
...
 @observe("set_range_button")
  def set_button_clicked(self,e):
        print(self.trait('t_pos').get_editor().high) #1
        self.trait('t_pos').get_editor().trait_set(high=123) #2
        print(self.trait('t_pos').get_editor().high) #3
...
```
Why is that? What would be correct way to update slider range?

**Comment by corranwebster** [comment]
The `get_editor()` call gets a new instance of the editor (a given trait can potentially appear in multiple Views or Items).

There are two solutions to the issue of a trait with mutable range bounds:

1. when defining the `Range` trait, instead of giving the numeric bound, give the name of the trait that holds the bound:
```
class Example(HasTraits):
    t_pos = Range(0, 't_high')
    t_high = Int(222)
```
you can then simply update `t_high`:
```
self.t_high = 123
```
The TraitsUI code is aware if this sort of usage, and should update the range to match.

2. If instead you want to keep the range of the model unchanged, but change the range displayed in the UI only, then you can pass the name of a a trait to the `low_name` and `high_name` parameters of the `RangeEditor`:
```
class Example(HasTraits):
    t_pos = Int()
    t_high = Int(222)

view = View(
    Item('t_pos', editor=RangeEditor(mode='slider', low=0, high_name='t_high'),
)
```

**Comment by KestutisMa** [comment]
Thank you, it worked!
I have another question if you don't mind: how to update window title?
I tried same way:
```
my_title = Str('t1')
..
view = View(
..
      title=my_title
)
...
self.my_title = 'new_title'
```
But it gave error:
```
traits.trait_errors.TraitError: The 'title' trait of a View instance must be a string, but a value of <traits.trait_types.Str object at 0x7f58c134a4f0> <class 'traits.trait_types.Str'> was specified.
```

**Comment by corranwebster** [comment]
To modify the title you need to use a `Handler` of some type and modify the `title` trait of the `UI` object.  There is an example which modifies the title to add a `*` when the content has changed in the documentation: https://docs.enthought.com/traitsui/traitsui_user_manual/handler.html (Example 9)

You can use that as a starting point, in your example you would need something like:
```
class MyHandler(Handler):
    def init(self, info):
        info.ui.title = info.object.my_title

    def object_my_title_changed(self, info):
        if info.initialized:
            info.ui.title = info.object.my_title

view = View(
    ...
    handler=MyHandler(),
)
```

**Comment by KestutisMa** [comment]
Thank you, it worked
