### ISSUE TITLE
Qt5 support

### ISSUE THREAD

**Issue by PAleksandrov** [enthought/traitsui#186]
Add a support for Qt5 (PyQt5).

**Comment by corranwebster** [comment]
@Tillsten See #165 for Python 3.  Qt5 isn't pressing for the Enthought devs at the moment, but we would happily accept backwards-compatible PRs to add support.

**Comment by nevion** [comment]
bump for qt5 (first) and python 3 second.

Qt5 is becoming the defacto Qt toolkit on linux(s) and many things are not linking to Qt4 anymore. Its getting quite hard to make sure all applications and libraries (like OpenCV who's highgui  module depends on Qt4 or Qt5) work together across Qt5 and occasionally python3.  Please up the priority of getting these things taken care of.

FYI IPython/Matplotlib have both of these working fine now adays.  It's about time Chaco does too.

**Comment by corranwebster** [comment]
For reference, see #241

**Comment by yanggehua** [comment]
Just being curious, does anyone has an agenda when the Qt5 support will be released for traitsui?   I have been using Anaconda's Python and recently upgraded to Spyder 3.0, which uses Qt5 for backend UI.  But because of this, I lost the ability to use libraries such as mayavi which depends on traitsui which in term only uses qt4.   Well, does anyone knows a temporary solution for this situation before the qt5-supported version is out?

**Comment by corranwebster** [comment]
There is a branch here: https://github.com/enthought/traitsui/pull/242  The current blocker for merging is CI testing.

This may not help you with mayavi, since as far as I know no effort has yet gone to making sure that it works on Qt5.

If you don't need strong interoperability (eg. can run mayavi in a separate process) running Mayavi under PySide w/Qt4 or WxPython may work for you.

**Comment by corranwebster** [comment]
Experimental support is available in master.  Closing this; issues with Qt5 should be raised as particular issues.
