### ISSUE TITLE
Memory and performance considerations

### ISSUE THREAD

**Issue by HeftyCoder** [enthought/traitsui#2039]
Hello, I've been toying with Traits UI in order to see if it fits my needs for a project I'm working on. As a test, I made a slightly ridiculous view of a simple configuration, just to test things out. I have the following classes:

```python

class AnotherConfig(HasTraits):
    something: float = Float(1, auto_set=False, enter_set=True)
    use_else: bool = Bool

class RandNodeConfig(HasTraits):
    scale: float = Float(1, auto_set=False, enter_set=True)
    use_seed: bool = Bool()
    seed: int = Int(0, auto_set=False, enter_set=True)
    con: AnotherConfig = Instance(klass=AnotherConfig, args=())
    direct: str = File()
    generate = Event

config = RandNodeConfig()

g1 = Group(
    *tuple(Item(name) for name in config.visible_traits()),
    *tuple(Item(name) for name in config.visible_traits()),
    *tuple(Item(name) for name in config.visible_traits()),
    *tuple(Item(name) for name in config.visible_traits()),
    *tuple(Item(name) for name in config.visible_traits()),
    *tuple(Item(name) for name in config.visible_traits()),
    *tuple(Item(name) for name in config.visible_traits()),
    Item("generate", show_label=False, editor=ButtonEditor(label="Generate!")),
    label="Config",
    scrollable=True
)

view = View(
    Group(g1, g1, g1, g1, 
        show_border=True, 
        layout='tabbed', 
        scrollable=True,
        label='Configuration'),
)

...

```

The code above generates a UI like the following:

<details>
<summary>UI example</summary>

![Screenshot_9](https://github.com/enthought/traitsui/assets/135903670/0acf39ed-4209-4d0f-a62e-d56053b8641b)

</details>

This "silly" duplication makes the generation of the UI:

- Take around 0.43 seconds to complete (for (6*7 + 1) * 4 = 176 items)
- Costs ~6 MBs for PySide2 and ~10 MBs for PySide6.

Now I realize I will probably never need something like this, it's borderline ridiculous. But since this is a big library, I thought it'd be better to ask here for any insight on why this happens. I am on Windows 10.

I suspect the memory problem is Qt related and probably has almost nothing to do with traits ui. But regarding the generation time, I doubt it'd take that long to generate the UI if it were only PySide6 (**tested with generating 500 radio buttons, takes around 0.05 seconds - 3 times the items take 1/10 of time**). Any insight on why this may happen would be appreciated. Given sufficient direction, I might take a look to see if this is fixable in any way, though I'm more inclined to believe that this might be too hard to fix.

**Comment by corranwebster** [comment]
Is the 0.43 seconds the start-up time from when you run the script? If so, I suspect that a fair chunk of that time is importing and initialization of the libraries. But it is also a known issue that complex UIs can be slow, due to https://github.com/enthought/traitsui/issues/1740 which you may be running into.

This is particularly the case if the `Instance` editors are (dynamically) creating default views as part of the initialization of each instance editor (not 100% sure if this is happening from a quick view of the code, but it seems likely).  If this is the case you may find that defining a default view on `AnotherConfig` makes things faster, something like:
``` python
class AnotherConfig(HasTraits):
    something: float = Float(1, auto_set=False, enter_set=True)
    use_else: bool = Bool

    view =  View(Item('something'), Item('use_else'))
```
This should share the `View` object between all of the different `Instance` editors.

As a a general rule, dynamic creation of `View` objects can be expensive: if you can it is better to use `enabled_when`, `visible_when` and `defined_when` if you can; or to define views which are associated with classes or use cases declaratively, and then choose which view to use dynamically.

**Comment by HeftyCoder** [comment]
Thanks for the swift reply. The 0.43 seconds is after importing and initialization, otherwise it takes around 0.67 seconds. Completely removing the nested Instance reduced it to around ~0.38 seconds.

I'm using `edit_traits` to embed the generated UI in another widget. I do have an `observer` using the `*` filter (any traits). I'm currently trying to decide whether I should delete the UI or store it for later usage. I'm making a visual scripting application, where each node may have configurable properties. Currently leaning on deleting the UI because I doubt what I tested above will ever be applicable in a real case scenario.

**Comment by corranwebster** [comment]
> I just found it interesting that UI generation seems to take a lot more time (around 30 times more) than simple Qt items.

There's generally a lot more going on than just the creation of the widgets.  In particular TraitsUI has the declarative layer (Views, Items, etc.) which is designed to be set up once (usually at import time) and then that is used for a template to create the objects that drive the UI (the UI object, Handlers, concrete Editors, etc.) that wrap the underlying toolkit components and handle dynamic changes based on application state, so you are looking at 3 layers of objects as opposed to one for straight Qt code.  And two of those layers are in Python rather than Qt/C++, which means a factor of 5-10 times slower for the same complexity.

It takes longer, but it's doing a lot more.  In your example, all of the fields which are viewing the same underlying trait are automatically linked up with the value on the object, and are all synchonised: change one and they all change.  To get the same effect with pure PyQt/PySide you'd need to do a lot more explicit work with signals and slots to hook things up, and additionally have some way of connecting to your underlying Python objects to synchronize the values.  If you did this, the code would still likely be much faster to start up, but it would be much more complex to write.

> I'm currently trying to decide whether I should delete the UI when I don't need it anymore or store it for later usage.

I think that it is generally worth keeping the `View` object around once you have created it unless you are extremely memory constrained.  There are ways to keep the `UI` object that you get from `edit_traits` around and re-use (and it does try to be efficient) but I'm not sure how much you will gain for the comparative expense - in general we don't bother - that code is there to make the `InstanceEditor` more efficient. It may be worth it if you are writing a wrapper widget that is designed to swap out the object being viewed on the fly, but on the other hand, that's more or less what an `InstanceEditor` is.

> EDIT: Is there a way to avoid Shadow Groups?

Not really, every `Group` will end up creating a `ShadowGroup`, and the problem is really with the `ShadowGroup` class using lots of `Delegate` traits.  The point of `ShadowGroup` is to allow some types of more dynamic UI creation with `Includes`. There may be ways to get the benefit without the cost, but that requires having someone dig in deeply to solve the problem.

In your example, you really only have 5 or 6 groups once you've factored out the groups associated with the `Instance` traits, so at that point I suspect that they aren't the problem; it's more likely just the sheer number of `Editors` being set up.  But if you are curious it should be possible to profile to see where the hotspots are.

So hopefully to sum up:
- TraitsUI is optimized for making it simple to _write_ straightforward UIs on top of a Traits model, trading developer time for run time speed
- In practise when we get beyond a CRUD view for a single object, or a controller for a visualization, or a dialog, we tend to use something like `Pyface`'s `Tasks` sub-package to build the wider application infrastructure

**Comment by HeftyCoder** [comment]
Thanks, this was very informative! My example was either way not realistic, too many editors were added for no reason. I was just trying to understand why the added layers would result in a massive slowdown, but I guess the internals of traits ui are that way.

For context, when I create 300 `radio buttons`, subscribe a function to their changed events and add them to their layouts, it takes around 0.03 seconds. For the traits example above, where 176 items are added, it takes 0.46 seconds (interestingly enough, not using a scrollable layout in traits reduces this time to 0.26 seconds). Anyway, that means that for around half the items, traits ui is around an order of magnitude slower than qt (creating widget + callback function + adding to layout). From that I can say the declarative layer and the ui layer make things  ~10 times slower. Granted, this is a really messy way to profile something, but I wanted to make quick comparisons.

I don't know the internal structures of traits ui and traits, but it seems that something else is slowing things down a lot other than the qt layer. I could be wrong, since I didn't apply any proper profiling. Nonetheless, feel free to close the issue. My question has been answered :)
