### ISSUE TITLE
FileEditor Drive Errors

### ISSUE THREAD

**Issue by VenturaFranklin** [enthought/traitsui#307]
Running the example [FileEditor_demo](https://github.com/enthought/traitsui/blob/master/examples/demo/Standard_Editors/FileEditor_demo.py) results in "Could not stat" errors while trying to connect to other drives. 
This only occurs for the custom view:
>Item('file_name', style='custom', label='Custom')

I am using:
Windows 7 x64
Python 2.7.9
traits==4.5.0
traitsui==5.1.0
PyQt4==4.11.4

The errors I get (many repeated over and over)
>attr-win[1474416294]:Could not get ADS for  C:\hiberfil.sys : Could not stat.
xattr-win[1474416298]:Could not get ADS for  Z:\ : Could not stat.
xattr-win[1474416312]:Could not get ADS for  W:\ : Could not stat.
xattr-win[1474416326]:Received error 1251  from CreateFile while attempting to o
pen U:\:mf_x

C: is the main drive, Z: is another internal drive, W: is a non connected network drive

The dialog is taking a while to open as it is running into these errors.

I can avoid the error by setting the root_path, not an ideal solution, because the the user can not leave this root_path:
FileEditor(root_path="path_to_root")

**Comment by corranwebster** [comment]
Thanks for the report.  The most likely culprit is Qt, unfortunately, since the custom editor is a fairly thin layer around a `QTreeView` with a `QFileSystemModel` for its model (see https://github.com/enthought/traitsui/blob/master/traitsui/qt4/file_editor.py#L192), coupled with (I'm guessing) Windows file system idiosyncracies - in particular the slowness may be in part from waiting for the non-connected network drive connection to time out.

For real-world use-cases I can think of two possible solutions.  One is to avoid the use of the "custom" view, and rely on the other views, plus the Pyface `FileDialog` class, where appropriate.  The second is that the root is dynamically updateable, so you could have a View with a Handler which provides a root via a "simple" `FileEditor` and a browser via a "custom" `FileEditor` and have changes to the root trait update the browser as needed, but that is significantly more complex.

**Comment by VenturaFranklin** [comment]
Thank you for the suggestion!

I went the Pyface route:
```
from pyface.qt import QtGui
from pyface.api import FileDialog, OK
control = QtGui.QWidget()
dlg = FileDialog(parent=control,
                 action='save as',
                 default_directory=config_path,
                 wildcard="*.yml")
if dlg.open() == OK:
    file_name = dlg.path
```
