### ISSUE TITLE
RangeEditor changes value entered manually in text box

### ISSUE THREAD

**Issue by achabotl** [enthought/traitsui#364]
Given the following example

```python
from traits.api import HasTraits, Float
from traitsui.api import Item, RangeEditor, View


class Slider(HasTraits):
    value = Float(5.)
    traits_view = View(Item('value', editor=RangeEditor(low=0., high=12.)))
    

if __name__ == "__main__":
    s = Slider()
    s.configure_traits()
```

which generates this UI:
![screen shot 2017-06-16 at 13 57 52](https://user-images.githubusercontent.com/479013/27240808-dd51da60-529b-11e7-9822-b830c972e7b6.png)

If enter the value 4
![screen shot 2017-06-16 at 13 57 56](https://user-images.githubusercontent.com/479013/27240822-e64d1062-529b-11e7-9271-1eca7265f93f.png)

and press Tab, I get the following:
![screen shot 2017-06-16 at 13 57 44](https://user-images.githubusercontent.com/479013/27240839-f045df0e-529b-11e7-82ab-e25117681722.png)

I assume this has to do with the resolution of the slider, because if I change `high` to 10, and and the value 4 in the text box I get a 4.0. It makes for a strange experience.

**Comment by achabotl** [comment]
It's TraitsUI 5.1.0 and Traits 4.6.

**Comment by corranwebster** [comment]
Yes, it's because under the covers the slider is actually storing integer values which then get scaled to a float by TraitsUI (at least on Qt) and so when the value is set it snaps to the nearest integer.  There's probably not a lot we can do about this short of writing our own version of the slider.

Maybe if we were are careful to set the range of integer values based on the floating point range so that when possible we hit only round values.  I can't think of a bullet-proff algorithm for this off the top of my head.
