### ISSUE TITLE
TableEditor row_factory insertion not working in Python 3.6

### ISSUE THREAD

**Issue by kSkip** [enthought/traitsui#483]
Below is a minimal reproduction of the problem encountered. This works as expected in Python 2.7. When you right click the table and select "add new item" it produces a new row containing a *Person* object with the attributes defined in *row_factory_kw*. In Python 3.6 it inserts an empty uneditable row, and does not appear to modify *people*.  (See screenshot)

```
from traits.api import (List, HasTraits, Unicode)
from traitsui.api import (View, UItem, TableEditor,
    TextEditor, ObjectColumn)

class Person(HasTraits):

    first_name = Unicode

    last_name = Unicode

class People(HasTraits):

    people = List

    traits_view = View(
        UItem('people', editor=TableEditor(
        columns=[
            ObjectColumn(
                name='first_name',
                editor=TextEditor()
            ),
            ObjectColumn(
                name='last_name',
                editor=TextEditor()
            )
        ],
        row_factory=Person,
        row_factory_kw={'first_name':'F','last_name':'L'}
        ))
    )

if __name__ == '__main__':
    People(
        people=[
            Person(first_name='Firstname', last_name='Lastname')
        ]
    ).configure_traits()
```

![screenshot from 2018-11-19 10-56-22](https://user-images.githubusercontent.com/10506768/48723144-7d7d3680-ebeb-11e8-8c06-ad87e0706be1.png)

**Comment by corranwebster** [comment]
Thanks for the report - as a quick check, what Qt API are you using in each case? PyQt4, PySide (or PyQt5 or PySide2)?

**Comment by corranwebster** [comment]
FWIW I can replicate on Python 3.5 + PyQt4.

Preliminary investigation shows the code to be running as expected

**Comment by corranwebster** [comment]
Right.  I know what's going on, and it's 2to3's fault.

The core of the problem is that the `TableEditor` has an `items()` method that is used in many places to return the list of items being edited (or a suitable proxy).  Unfortunately 2to3 sees a call to `items()` and thinks "Aha! An old style dictionary `items()` call! I need to reproduce the Python 2 behaviour by wrapping it in a call to `list`!"

Which would be fine, except that traits lists aren't `list`s, but a special subclass, so calling `list(editor.items())` _copies_ the list, whereupon everything goes to heck because we are modifying an ephemeral object, not the real thing.

The immediate workaround is probably to use the `TabularEditor` if its more limited feature set will suit your need; if don't allow items to be inserted into the table and add a button or some other UI element that adds a new row to the underlying list directly.

A fix would be to convince 2to3 to not mess with the `items()` calls in the `TableEditor` code.

The correct fix is to get rid of the use of 2to3, but that is much more involved.

**Comment by kSkip** [comment]
Thanks for looking into that. I am using PyQt4 with Python 3.6.

Yes, I have already implemented a work around with a ui button that adds the row itself, and everything is fine. I may try the TabularEditor though.
