### ISSUE TITLE
Broken web and documentation links

### ISSUE THREAD

**Issue by sandhya-sago** [enthought/traitsui#617]
1.  On github page
https://github.com/enthought/traitsui
The following links are not working:
User Manual http://docs.enthought.com/traitsui/traitsui_user_maunal
Tutorial http://docs.enthought.com/traitsui/tutorial

1. Similar with documentation at https://docs.enthought.com/traitsui/
The following links are not working: 
User Manual http://docs.enthought.com/traitsui/traitsui_user_maunal
Tutorial http://docs.enthought.com/traitsui/tutorial

1. On the tutorial web page:
https://docs.enthought.com/traitsui/tutorials/traits_ui_scientific_app.html
The following links are not working.
http://code.enthought.com/traits/
[4]	The traits and traitsUI user guide: http://code.enthought.com/traits

**Comment by corranwebster** [comment]
Thanks for the report.  The fixes look like:

1. These are typos ("maunal" instead of "manual", "tutorial" instead of "tutorials") in the main [README.rst](https://github.com/enthought/traitsui/blob/master/README.rst) file.  So this is an easy fix.

2. The documentation just grabs the content of the README, so fixing 1 should fix 2 once the documentation is re-built.

3. the references to `code.enthought.com` should be replaced with references to `docs.enthought.com`.  The file to fix them in is here: https://github.com/enthought/traitsui/blob/master/docs/source/tutorials/traits_ui_scientific_app.rst

This would be a good first issue for you to fix.  To test the documentation build, the easiest way is to install `click` into your Python environment and then:
```
python etstool.py install --runtime=3.6 --toolkit=pyqt
```
which creates a testing environment called something like `traitsui-test-pyqt-3.6` and then switch into that environment and install `sphinx`.  You should then be able to cd into docs and use the standard `make html` command to build all the documentation.

Since these are not code issues, you can add `[ci skip]` at the end of your commit messages to avoid running CI.

**Comment by corranwebster** [comment]
Fixed by #619
