### ISSUE TITLE
Test failure - QCoreApplication::exec: The event loop is already running

### ISSUE THREAD

**Issue by opoplawski** [enthought/traitsui#640]
Trying to update the Fedora package, getting the following error:
```
BUILDSTDERR: test_live_view_application_eventloop_close (traitsui.tests.test_view_application.TestViewApplication) ... QCoreApplication::exec: The event loop is already running
BUILDSTDERR: ok
BUILDSTDERR: test_live_view_application_ok (traitsui.tests.test_view_application.TestViewApplication) ... /var/tmp/rpm-tmp.Zvn4u6: line 42:  2048 Segmentation fault      (core dumped) PYTHONPATH=/builddir/build/BUILDROOT/python-traitsui-6.1.2-1.fc32.noarch/usr/lib/python3.8/site-packages nosetests-3.8 -v
```
I'm not at all familiar with that Qt error - any ideas?

**Comment by corranwebster** [comment]
Are you getting the error consistently, or only on occasional runs?

Which version of Python, and which Python Qt backend are you using?

In general the tests are not in a good state because many of them do not clean up after themselves, so it is likely that the cause of this test failure is something that occurred in a different test and only failed when a proper clean-up was done.  See #636 for general issues.

Possible steps to help diagnose this particular test would include importing and enabling `faulthandler` for `test_view_application` to at least narrow down where things are happening.

**Comment by opoplawski** [comment]
Our builds are working now - perhaps due to a switch to qt5 stuff.
