### ISSUE TITLE
from traitsui.wx.editor import Editor: failure

### ISSUE THREAD

**Issue by CdeMills** [enthought/traitsui#676]
Hello
I'm trying to run the code at
https://docs.enthought.com/traitsui/tutorials/traits_ui_scientific_app.html#from-graphical-to-interactive
in particular the code snippet #8. This fails at
from traitsui.wx.editor import Editor
with
PythonObject = wx.CustomDataFormat('PythonObject')
wx._core.PyNoAppError: The wx.App object must be created first!

System Context: Ubuntu 18.04 LTS, Python 3.6.8, python3-wxgtk4.0/bionic 4.0.1+dfsg-2 amd64
Installed with pip3 in a venv:
cycler==0.10.0
kiwisolver==1.1.0
matplotlib==3.1.1
numpy==1.17.3
pkg-resources==0.0.0
pyface==6.1.2
pyparsing==2.4.2
PySimpleGUI==4.4.1
python-dateutil==2.8.0
scipy==1.3.1
six==1.12.0
traits==5.1.2
traitsui==6.1.3

Any idea ? Or update to the tutorial ?

Regards

Pascal

**Comment by corranwebster** [comment]
Looking at your environment, I don't see wxPython; if `python3-wxgtk4.0` includes wxPython then I am guessing that the problem might be that you have wxPython 4.  At the moment TraitsUI only supports wxPython 3 (although there are branches which have wxPython 4 support).

If you don't want to use wxPython, you can install PyQt (or experimentally PySide2) and use those, although some parts of the tutorial won't work because they assume wxPython, but the ideas are the same.

**Comment by CdeMills** [comment]
Hello,
thanks for your reply. The latest release of wxPython3 is 3.0.2 in Nov 2014 on sourceforge. OR is there something newer ?
Regards
Pascal

**Comment by corranwebster** [comment]
No nothing newer - it's quite old.  At Enthought most of our work is done with the Qt TraitsUI backend rather than Wx these days, so the Wx backend has fallen a bit behind - there's unfortunately no graceful way to support both Wx 3 and Wx 4.

There is a Qt version of the tutorial here: https://github.com/FelixHartmann/traitsui-tutorial-qt

**Comment by CdeMills** [comment]
Matplotlib API changed since this tutorial was written. I made a few corrections; how can the traitsui tutorial be updated to reflect my changes ?

Regards
Pascal

**Comment by SeyhanDBG** [comment]
@CdeMills Could you please share your updates?

**Comment by corranwebster** [comment]
We would happily merge a pull request with fixes as needed.

Also to update the original issue: the master branch now supports wxPython 4 and we should have wxPython 4 support in the next release.

**Comment by rahulporuri** [comment]
closing this issue as we have dropped support for wxpython 3 and im not seeing this error on python 3 + wxpythnon 4 any longer.
