### ISSUE TITLE
format_func applied to Item's for which it was not specified

### ISSUE THREAD

**Issue by notmatthancock** [enthought/traitsui#790]
The example below on TraitsUI 6.1.3 produces the window:

![image](https://user-images.githubusercontent.com/1588456/80219284-dc788380-8607-11ea-8558-205db3fd10df.png)

where the second Item has had the `format_func` (only specified in the first Item) applied. A workaround is to specify `format_func=lambda s: s` in the second Item.

```python
from traits.api import *
from traitsui.api import *

class Foo(HasStrictTraits):
    thing = Str('a_thing')
    things = Str('one, two, three_four')

    traits_view = View(
        Item('thing', format_func=lambda s: s.replace('_', ' ').title()),
        Item('things')
    )

Foo().configure_traits()
```

**Comment by corranwebster** [comment]
Replicated.  And really odd.

**Comment by corranwebster** [comment]
Right.  I know what's going on.

The proposed work-around isn't really a work-around, as you will need to apply that to _every_ `Item` which edits a `Str` in your app, even ones you don't control. A better workaround is just to declare en editor for the `Item` with the format func:
```
Item('thing', format_func=lambda s: s.replace('_', ' ').title(), editor=TextEditor())
```
or perhaps even more clearly:
```
Item('thing', editor=TextEditor(format_func=lambda s: s.replace('_', ' ').title()))
```
since `format_func` is really a trait on the Editor and being able to set it in the `Item` is a convenience.

OK.  Now to explain what is going on:

- for some reason (supposed efficiency? historical assumptions which have changed?) the default editor for a `Str` trait is defined in Traits, and are _cached_ based on the trait metadata values that the editor factory knows about.  See https://github.com/enthought/traits/blob/99d83bd8134bcb97b991724fde7bb5d6a24962de/traits/editor_factories.py#L44-L54
- so there is precisely one `TextEditor` instance (this is the editor _factory_) shared across both of the `Str` traits, since their `auto_set` and `enter_set` metadata is the same.
- which should be fine, except that `format_func` (and `format_str` and `invalid`) are traits on the editor _factory_ but not on the TraitsUI base `Editor` class, so when TraitsUI sees them in an `Item` it goes and modifies the _factory_ in-place. See https://github.com/enthought/traitsui/blob/3e2ce8604f8916ac68025c78fdc1985001d9c18b/traitsui/qt4/ui_panel.py#L851-L862
- but that factory is shared
- so all the `Str` traits get the same `format_func`
- the proposed workaround basically sets the value back to the default, but that's really dodgy and liable to upset if the view gets rearranged

So how to fix:

1. Traits should stop trying to cache default Editor factories.  It's been a constant source of weird bugs.
2. Format functions, format strings and `invalid` trait names should live on the `Editor`, not the `Editor` factory (by all means, make it so that they can be set in the factory, but the `Editor` is the source of truth).
3. the `ui_panel.py` code should change the values in the `Editor` after it is created, not on the Editor factory.  Editor factories may potentially be shared between Items.

Fixing either (1) or (2 and 3) should resolve the problem.

**Comment by notmatthancock** [comment]
Thanks for the details and a working workaround!

**Comment by ievacerny** [comment]
This seems to be fixed by https://github.com/enthought/traits/pull/1032
