### ISSUE TITLE
`ModelView` should allow null models

### ISSUE THREAD

**Issue by danieljfarrell** [enthought/traitsui#805]
Does TraitsUI allow `None` to be passed to `ModelView`? It seems not from this code. It would be a useful feature; allowing the developer to handle null cases without having to introduce a specific null type as shown below. Is there a workaround in Traits to avoid the `AttributeError` raised in this contrived example?

```python
    from traits.api import HasTraits, Str, Instance, on_trait_change
    from traitsui.api import ModelView, View, Item, VGroup, Label


    class Book(HasTraits):
        name = Str()
    
    # Need to introduce this null type to handle 'None' case
    class NullBook(Book):
        name = 'No selection'
        
    
    class SelectedBookDetailsView(ModelView):
        
        model = Instance(Book)

        name = Str()
        
        def _name_default(self):
            return '-'
        
        @on_trait_change('model')
        def on_update(self):
            if self.model is None:
                self.name = 'No selection'
            else:
                self.name = 'Selected: `{}`'.format(self.model.name)
        
        def default_traits_view(self):
            return View(
                VGroup(
                    Label('Book'),
                    Item('model.name', style='readonly')
                )
            )

    view = SelectedBookDetailsView(model=Book(name='Item 1'))
    view.configure_traits()

    # Using `NullBook` to mean `None`
    view = SelectedBookDetailsView(model=NullBook())
    view.configure_traits()
    
    # Using Python's null type
    # AttributeError: 'NoneType' object has no attribute 'base_trait'
    view = SelectedBookDetailsView(model=None)
    view.configure_traits()
```

**Comment by corranwebster** [comment]
No, `None` is not intended to work as a `model` value in a `ModelView`.  The problem is that the view expects the `model` be a `HasTraits` and to have trait `name`.  The second problem can be fixed by using `name` instead of `model.name` in the view (which is what you probably meant to write anyway, based on the code):
```
    def default_traits_view(self):
        return View(
            VGroup(
                Label('Book'),
                Item('name', style='readonly')
            )
        )
```
The cause of the error is that the `ModelView` adds both the `ModelView` and the `model` into the Traits UI context dictionary, and every value in the context is assumed to be a HasTraits and have listeners hooked up to all of its traits.  Fortunately, you can override this by adding the following to your ModelView:
```
    def trait_context(self):
        return {'object': self}
```
Then your example works as you expect it to.

**Comment by danieljfarrell** [comment]
Oh yes, I intended `object.name` in that example. Thanks @corranwebster! I will play around with those idea tomorrow.
