### ISSUE TITLE
Document that enabled_when / visible_when don't update for nested traits

### ISSUE THREAD

**Issue by notmatthancock** [enthought/traitsui#833]
If the string provided to `enabled_when` or `visible_when` on an `Item` refers to a nested trait, then the enabled-ness or visibility don't update when the nested trait value changes (see example below). This feels inconsistent with the behavior of `on_trait_change` or `depends_on`.

A typical workaround is to add a shadow trait to the parent class (for example in the below, adding a trait `a_is_magic_number = Property(depends_on='a:x')`. This workaround feels like redundant work, though.

#### Example

```python
from traits.api import *
from traitsui.api import *


class A(HasTraits):
    number = Int()
    is_magic_number = Property(depends_on='number')

    def _get_is_magic_number(self):
        return self.number == 1729

    traits_view = View(Item('number'))


class B(HasTraits):
    a = Instance(A, ())
    done = Button()

    traits_view = View(
        UItem('a', style='custom'),
        UItem('done', enabled_when='a.is_magic_number'),
    )


B().configure_traits()
```

**Comment by corranwebster** [comment]
The `enabled_when`, `visible_when`, etc. traits aren't trait listeners, but instead are Python _expressions_.  This allows more flexibility in how you express the condition (eg. you could write `enabled_when = 'a.number == 1729'`, although that would still fail in this case, butt will with the work-around below), but at the expense of not knowing what the dependencies are.  Determining the dependencies of a Python expression _is_ technically possible, but would require a lot of the code analysis found in the Codetools ETS package, and we don't want to depend on that in TraitsUI.  In a perfect world other decisions may have been made about how the API should work, but so much code now depends on the ability to use arbitrary expressions that it would be impssible to change that.

Instead `enabled_when` etc. are evaluated by an `_anytrait_changed` handler which listens to everything in the context.  So if you had used a `ModelView` instead, with `a` replaced by `model`, it would have worked!  So one solution, if you don't expect `a` to be replaced by a different object during the lifetime of the UI is to do something like this:
```
class B(HasTraits):
    a = Instance(A, ())
    done = Button()

    def trait_context(self):
        return {'object': self, 'a': self.a}

    traits_view = View(
        UItem('a', style='custom'),
        UItem('done', enabled_when='a.is_magic_number'),
    )
```
which means that `enabled_when` now gets updated when any trait of `a` gets changed.

Hopefully this is a good enough work around.  Unfortunately, I don't think there's any reasonable way to make the first example work as-is.

**Comment by notmatthancock** [comment]
Understood, thanks. This is helpful.

Is the following:

> Instead enabled_when etc. are evaluated by an _anytrait_changed handler which listens to everything in the context.

documented somewhere?

Also, I have not seen `trait_context` implemented as a function like that -- only as a dictionary supplied to `configure_traits`. Is that documented somewhere, and if not, would it make sense to add as a note to the context parameter of the configure_traits docstring?

**Comment by aaronayres35** [comment]
I've renamed this issue to make it clear that this should bee resolved by documenting this behavior somewhere (especially now that it has effectively been raised multiple times - see #1529).
I had one thought of a potential fix to change the behavior, see https://github.com/enthought/traitsui/issues/1529#issuecomment-794563132, but as the comment describes I am a bit wary of that approach.

In any case, the documentation could use more details on how enabled_when/visible_when work and common things like this to look out for

**Comment by corranwebster** [comment]
I think listening to nested traits is probably not going to be practical (how deep down the object graph do you go?). 
The immediate solution here is to have better documentation of `enabled_when` and `visible_when`.

There is one other option which might work which is to look at `enabled_when`/`visible_when` expressions and see if they look like an extended trait name (ie. `foo.bar.baz`) and then hook up listeners directly to them and assume that they hold truthy/falsey values.  You'd still run into issues because you'd need to say things like `object.a.is_magic_number`, but that's matching what you'd need to do for an `Item`, so it's not that out there.

But you'd still need the documentation.

**Comment by rahulporuri** [comment]
@corranwebster looking at the code, i don't understand who uses the `trait_context` method and how. See `edit_traits` and `configure_traits` which just set `context = self` if `context=None` is those methods are called - instead of using the `trait_context` method.

https://github.com/enthought/traits/blob/eb0027f3d6a57968104949e5a5fc5d7db9d4a577/traits/has_traits.py#L1731-L1732
https://github.com/enthought/traits/blob/eb0027f3d6a57968104949e5a5fc5d7db9d4a577/traits/has_traits.py#L2086-L2087

I was going to open an issue in traits regarding updating the documentation of `edit_traits` and `configure_traits` method docstrings like @notmatthancock mentioned above but given the confusion, i'll hold off.
